document.writeln("<footer class='footer'>");
document.writeln("	<div class='footer__row display_none'>");
document.writeln("		<div class='footer__line'>");
document.writeln("			<ul class='footer__l'>");
document.writeln("				<li><a href='#'>赞助计划</a></li>");
document.writeln("				<li><a href='#'>资金安全保障</a></li>");
document.writeln("				<li><a href='#' title='媒体联系方式'>媒体联系方式</a></li>");
document.writeln("			</ul>");
document.writeln("			<ul class='footer__r'>");
document.writeln("				<li><a class='js-mail' href='mailto:#'>info@15151.com</a></li>");
document.writeln("				<li><a href='#'>外汇插件</a></li>");
document.writeln("				<li><a href='#'>网站地图</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class='footer__nav'>");
document.writeln("		<div class='footer__cols'>");
document.writeln("			<ul class='footer__col'>");
document.writeln("				<li><a href='http://t.gqfxcn.com' target='_blank'>登录</a></li>");
document.writeln("				<li><a href='http://t.gqfxcn.com/register' target='_blank'>注册</a></li>");
document.writeln("			</ul>");
document.writeln("			<div class='footer__sep'></div>");
document.writeln("			<ul class='footer__col'>");
document.writeln("				<li><a href='../clients/deposit.html'>入金</a></li>");
document.writeln("				<li><a href='../clients/withdrawal.html'>出金</a></li>");
document.writeln("			</ul>");
document.writeln("			<div class='footer__sep'></div>");
document.writeln("			<ul class='footer__col'>");
document.writeln("				<li><a href='javascript:void(0)'>优惠活动</a></li>");
document.writeln("				<li><a href='javascript:void(0)'>GQFX积分奖励</a></li>");
document.writeln("			</ul>");
document.writeln("			<div class='footer__sep'></div>");
document.writeln("			<ul class='footer__col'>");
document.writeln("				<li><a href='../transaction/ea-transaction.html'>EA交易</a></li>");
document.writeln("				<li><a href='../transaction/independent-transaction.html'>自主交易</a></li>");
document.writeln("			</ul>");
document.writeln("			<div class='footer__sep'></div>");
document.writeln("			<ul class='footer__col'>");
document.writeln("				<li><a href='../transaction/social-transaction.html'>社交交易</a></li>");
document.writeln("				<li><a href='../platforms/transaction-app.html'>社交交易App</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class='footer__new'>");
document.writeln("		<div class='footer__text-container'>");
document.writeln("			<div class='footer__text-container'>");
document.writeln("				<div class='qr-code'>");
document.writeln("					<ul style='padding-left: 0px;'>");
document.writeln("						<li>");
document.writeln("							<img src='../img/weibo.png' title='GQFX智远集团官方微博' alt='GQFX智远集团官方微博'>");
document.writeln("							<p>微博</p>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<img src='../img/weichat.jpg' title='GQFX智远集团官方微信' alt='GQFX智远集团官方微信'>");
document.writeln("							<p>微信</p>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("				<div class='content'>");
document.writeln("						<p><b>合作性：</b>本网站外汇运营由伯利兹GQ Capital Incorporated运营，注册地址位于中美洲伯利兹城库克街5号，由国际金融服务委员会监管，牌照：<a class='link link_type_pdf link_color_gray ' href='#'>IFSC / 60/445 / TS / 17</a>。</p>");
document.writeln("						<p>本网站的信息可被世界各地访问，不是针对任何国家或管辖区的居民而分发，或其使用将违反当地法律或法规。</p>");
document.writeln("						<p><b>风险警告：</b>外汇交易可能对您选择投资的资本带来极大的风险，请确保您已经阅读并完全理解GQFX的<a class='link link_type_pdf link_color_gray' href='../pdf/TOB v180303 ENCN.pdf' target='_blank'>业务条款</a>和<a class='link link_type_pdf link_color_gray ' href='../pdf/RDS v180220 ENCN.pdf' target='_blank'>风险披露</a></p>");
document.writeln("				</div>");
document.writeln("				<p class='pdf'>");
document.writeln("					<a class='link link_color_gray' href='../support/terms-and-conditions.html'>条款和条件</a>");
document.writeln("					<a class='link link_type_pdf link_color_gray ' href='../pdf/Privacy v180223 ENCN.pdf' target='_blank'>隐私政策</a>");
document.writeln("					<a class='link link_type_pdf link_color_gray ' href='../pdf/AML v180220 ENCN.pdf' target='_blank'>反洗钱政策</a>");
document.writeln("					<a class='link link_type_pdf link_color_gray ' href='../pdf/COI v180305 ENCN.pdf' target='_blank'>利益冲突政策</a>");
document.writeln("					<a class='link link_type_pdf link_color_gray'  href='../pdf/BEP v180305 ENCN.pdf' target='_blank'>最佳执行政策</a>");
document.writeln("				</p>");
document.writeln("				<h5>© 2015 -2017 GQ CAPITAL INCORPORATED | LICENSE NO. IFSC/60/445/TS/17</h5>");
document.writeln("				<img src='../img/siteSealImage.png'>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</footer>");