
document.writeln("<header id='header' class='header'>");
document.writeln("	<div class='header_nav-opacity'>");
document.writeln("		<div class='grid__container clearfix'>");
document.writeln("			<ul class='header__nav-r'>");
document.writeln("				<li class='header__nav-item header__langs'>");
document.writeln("					<a  class='header__nav-link header__langs-link' href='#'>简体中文</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("<div class='header_content'>");
document.writeln("		<a href='../index.html'><img class='header__logo-ball' src='../img/gqfx_logo_mini.png' alt=''></a>");
document.writeln("		<ul class='header__action-list'>");
document.writeln("			<li	class='header__action-item'>");
document.writeln("					<a class='header__action' href='http://t.gqfxcn.com' target='_blank' rel='nofollow'>登&nbsp;&nbsp;录</a>");
document.writeln("			</li>");
document.writeln("			<li class='header__action-item'>");
document.writeln("				<a class='header__action header__action_type_primary' href='http://t.gqfxcn.com/register' target='_blank' rel='nofollow'>开立账户</a>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</header>");
document.writeln("<nav class='menu'>");
document.writeln("		<ul class='menu__list'>");
document.writeln("			<li class='menu__item'>");
document.writeln("				<div class='menu__btn'>");
document.writeln("					<a class='menu__link' href='javascript:void(0)'>");
document.writeln("						<span class='menu__text'>关于我们</span>");
document.writeln("					</a>");
document.writeln("					<span class='menu__deco'></span>");
document.writeln("				</div>");
document.writeln("				<div class='menu__sub menu__sub_cols_4'>");
document.writeln("					<ul class='menu__sub-col'>");
document.writeln("						<li class='menu__sub-item'><a href='../about/gqfx.html'>GQFX</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='../about/license.html'>牌照和监管</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='../about/security.html'>资金安全保障</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='../about/dynamic.html'>GQFX动态</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class='menu__item menu__itembefore'>");
document.writeln("				<div class='menu__btn'>");
document.writeln("					<a class='menu__link' href='javascript:void(0)'>");
document.writeln("						<span class='menu__text'>奖励和优惠</span>");
document.writeln("					</a>");
document.writeln("					<span class='menu__deco'></span>");
document.writeln("				</div>");
document.writeln("				<div class='menu__sub menu__sub_cols_3'>");
document.writeln("					<ul class='menu__sub-col'>");
document.writeln("						<li class='menu__sub-item'><a href='javascript:void(0)'>GQFX积分奖励</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='javascript:void(0)'>优惠活动</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a class=' ' href='javascript:void(0)'>常见问题（奖励和优惠）</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class='menu__item menu__itembefore'>");
document.writeln("				<div class='menu__btn'>");
document.writeln("					<a class='menu__link' href='javascript:void(0)'>");
document.writeln("						<span class='menu__text'>交易</span>");
document.writeln("					</a>");
document.writeln("					<span class='menu__deco'></span>");
document.writeln("				</div>");
document.writeln("				<div class='menu__sub menu__sub_cols_3'>");
document.writeln("					<ul class='menu__sub-col'>");
document.writeln("						<li class='menu__sub-item'><a href='../transaction/independent-transaction.html'>自主交易</a></li>");
document.writeln("						<li class='menu__sub-item'><a href='../transaction/ea-transaction.html'>EA交易</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='../transaction/social-transaction.html'>社交交易(Social Trading)</a></li>");
document.writeln("						<li class='menu__sub-item'><a href='javascript:void(0)'>交易者计算器</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("							<li class='menu__sub-item menu__sub-item_titled_yes'>");
document.writeln("								<div class='menu__sub-title'>交易条件</div>");
document.writeln("								<ul class='list list_type_disc'>");
document.writeln("									<li><a href='../transaction/forex.html'>外汇/差价合约概览</a></li>");
document.writeln("								<li><a href='../transaction/ensure-gold.html'>保证金</a></li>");
document.writeln("									<li><a href='../transaction/swap-rate.html'>掉期率</a></li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("				</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class='menu__item menu__itembefore'>");
document.writeln("				<div class='menu__btn'>");
document.writeln("					<a class='menu__link' href='javascript:void(0)'>");
document.writeln("						<span class='menu__text'>投资</span>");
document.writeln("					</a>");
document.writeln("					<span class='menu__deco'></span>");
document.writeln("				</div>");
document.writeln("			<div class='menu__sub menu__sub_cols_3'>");
document.writeln("					<ul class='menu__sub-col'>");
document.writeln("						<li class='menu__sub-item menu__sub-item_titled_yes'>");
document.writeln("							<div class='menu__sub-title'>资产管理(PAMM)</div>");
document.writeln("							<ul class='list list_type_disc'>");
document.writeln("								<li><a href='../investment/pamm-list.html'>PAMM账户排行榜</a></li>");
document.writeln("								<li><a href='../investment/about-pamm.html'>关于PAMM账户的更多详情</a></li>");
document.writeln("								<li><a href='../investment/pamm-comment.html'>PAMM账户评论</a></li>");
document.writeln("								<li><a href='../investment/investment-terms.html'>投资条件</a></li>");
document.writeln("								<li class='menu__sub-checked-by-auditor'><a href='javascript:void(0)'>已经过审核验证</a></li>");
document.writeln("							</ul>");
document.writeln("						</li>");
document.writeln("				</ul>");
document.writeln("				<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item menu__sub-item_titled_yes'>");
document.writeln("							<div class='menu__sub-title'>资产组合管理(MAM)</div>");
document.writeln("							<ul class='list list_type_disc'>");
document.writeln("								<li><a href='../investment/mam-list.html'>资产组合账户排行榜</a></li>");
document.writeln("								<li><a href='../investment/constructor.html'>组建自己的资产组合账户</a></li>");
document.writeln("								<li><a href='../investment/about-mam.html'>关于资产组合账户的更多详情</a></li>");
document.writeln("								<li><a href='../investment/investment-terms.html'>投资条件</a></li>");
document.writeln("								<li class=' menu__sub-checked-by-auditor'><a href='javascript:void(0)'>已经过审核验证</a></li>");
document.writeln("							</ul>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='../investment/closed-product.html'>封闭式产品</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class='menu__item menu__itembefore'>");
document.writeln("				<div class='menu__btn'>");
document.writeln("					<a class='menu__link' href='javascript:void(0)'>");
document.writeln("						<span class='menu__text'>交易平台</span>");
document.writeln("					</a>");
document.writeln("					<span class='menu__deco'></span>");
document.writeln("				</div>");
document.writeln("				<div class='menu__sub menu__sub_cols_3'>");
document.writeln("					<ul class='menu__sub-col'>");
document.writeln("						<li class='menu__sub-item'><a href='../platforms/windows-mt4.html'>windows MT4</a></li>");
document.writeln("						<li class='menu__sub-item'><a class=' ' href='../platforms/android-app.html'>Android OS</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='../platforms/mac-mt4.html'>Mac MT4</a></li>");
document.writeln("						<li class='menu__sub-item'><a href='../platforms/transaction-app.html'>社交交易App</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='../platforms/ios-app.html'>IOS</a></li>");
document.writeln("						<li class='menu__sub-item'><a href='../platforms/problem.html'>常见问题（软件安装使用）</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class='menu__item menu__itembefore'>");
document.writeln("			<div class='menu__btn'>");
document.writeln("					<a class='menu__link' href='javascript:void(0)'>");
document.writeln("						<span class='menu__text'>客户</span>");
document.writeln("					</a>");
document.writeln("					<span class='menu__deco'></span>");
document.writeln("				</div>");
document.writeln("				<div class='menu__sub menu__sub_cols_3'>");
document.writeln("					<ul class='menu__sub-col'>");
document.writeln("						<li class='menu__sub-item menu__sub-item_titled_yes'>");
document.writeln("							<div class='menu__sub-title'>出/入金</div>");
document.writeln("							<ul class='list list_type_disc'>");
document.writeln("								<li><a href='../clients/deposit.html'>入金</a></li>");
document.writeln("								<li><a href='../clients/withdrawal.html'>出金</a></li>");
document.writeln("								<li><a href='../clients/transfer-accounts.html'>账户间转账</a></li>");
document.writeln("								<li><a href='../clients/problem.html'>常见问题（出/入金）</a></li>");
document.writeln("							</ul>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("							<li class='menu__sub-item'><a href='../clients/glossary.html'>常用词汇表</a></li>");
document.writeln("							<li class='menu__sub-item'><a href='../clients/economic-calendar.html'>财经日历</a></li>");
document.writeln("							<li class='menu__sub-item'><a href='http://gqfx.asia' target='_blank'>外汇入门-智远圈</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("							<li class='menu__sub-item'><a href='../clients/knowledge.html'>知识</a></li>");
document.writeln("							<li class='menu__sub-item'><a href='../clients/news.html'>市场新闻</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class='menu__item menu__itembefore'>");
document.writeln("				<div class='menu__btn'>");
document.writeln("					<a class='menu__link' href='javascript:void(0)'>");
document.writeln("						<span class='menu__text'>合作伙伴</span>");
document.writeln("					</a>");
document.writeln("					<span class='menu__deco'></span>");
document.writeln("				</div>");
document.writeln("				<div class='menu__sub menu__sub_cols_3'>");
document.writeln("					<ul class='menu__sub-col'>");
document.writeln("							<li class='menu__sub-item'><a href='../partnership/market-representative.html'>市场代表</a></li>");
document.writeln("							<li class='menu__sub-item'><a href='../partnership/white-label.html'>白标</a></li>");
document.writeln("						</ul>");
document.writeln("						<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("							<li class='menu__sub-item'><a href='../partnership/cooperation.html'>营销合作</a></li>");
document.writeln("						</ul>");
document.writeln("						<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("							<li class='menu__sub-item'><a class=' ' href='../partnership/money-manager.html'>资金经理</a></li>");
document.writeln("						</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class='menu__item menu__itembefore'>");
document.writeln("				<div class='menu__btn'>");
document.writeln("					<a class='menu__link' href='javascript:void(0)'>");
document.writeln("						<span class='menu__text'>支持</span>");
document.writeln("					</a>");
document.writeln("					<span class='menu__deco'></span>");
document.writeln("				</div>");
document.writeln("				<div class='menu__sub menu__sub_cols_3'>");
document.writeln("					<ul class='menu__sub-col'>");
document.writeln("						<li class='menu__sub-item'><a href='../support/sitemap.html'>网站地图</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='../support/problem.html'>常见问题</a></li>");
document.writeln("					</ul>");
document.writeln("					<ul class='menu__sub-col menu__sub-colbefore'>");
document.writeln("						<li class='menu__sub-item'><a href='../support/contact-us.html'>联系我们</a></li>");
document.writeln("					</ul>");
document.writeln("					</div>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("</nav>");