document.writeln("<div class='sidebar-box'>");
document.writeln("		<ul>");
document.writeln("		  <li>");
document.writeln("			<div class='side-hoverout' style='width: 0px; overflow: hidden;'>");
document.writeln("			  <a href='../support/contact-us.html' >");          
document.writeln("				<div class='side-hover-w'>");
document.writeln("				  <i class='side-icon side-i6'></i>");
document.writeln("				  <p>邮件咨询</p>");
document.writeln("				</div>");
document.writeln("			  </a>");
document.writeln("			  <a href='http://wpa.b.qq.com/cgi/wpa.php?ln=1&key=XzgwMDE2MDEzNV80NDcyMjNfODAwMTYwMTM1XzJf' target='_blank' >");            
document.writeln("				<div class='side-hover-w'>");
document.writeln("				  <i class='side-icon side-i7'></i>");
document.writeln("				  <p>QQ客服</p>");
document.writeln("				</div>");
document.writeln("			  </a>");
document.writeln("			</div>");
document.writeln("			<a href='javascript:void(0)' rel='nofollow' >");
document.writeln("			  <i class='side-icon side-i1'></i>");
document.writeln("			  <p>咨询客服</p>");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		  <li class='li-line'>");
document.writeln("			<a href='javascript:void(0)'>");
document.writeln("			  <i class='side-icon side-i2'></i>");
document.writeln("			  <p>官方微信</p>");
document.writeln("			</a>");   
document.writeln("			<div class='side-hoverout wex-anim-hf' style='width: 0px; overflow: hidden;'>");
document.writeln("			  <p class='side-weix-anim'>");
document.writeln("			  </p>");
document.writeln("			</div>");
document.writeln("		  </li>");
document.writeln("		  <li  class='li-line-bottom'>");
document.writeln("			<div class='side-hoverout' style='width: 0px; overflow: hidden;'>");
document.writeln("			  <a href='http://t.gqfxcn.com/register'  rel='nofollow' target='_blank' class='external'>");        
document.writeln("				<div class='side-hover-w'>");
document.writeln("				  <i class='side-icon side-i8'></i>");
document.writeln("				  <p>真实账户</p>");
document.writeln("				</div>");
document.writeln("			  </a>");
document.writeln("			  <a href='http://t.gqfxcn.com/registerMock'  rel='nofollow' target='_blank' class='external'>");          
document.writeln("				<div class='side-hover-w'>");
document.writeln("				  <i class='side-icon side-i9'></i>");
document.writeln("				  <p>模拟账户</p>");
document.writeln("				</div>");
document.writeln("			  </a>");
document.writeln("			</div>");
document.writeln("			<a href='http://t.gqfxcn.com/register'  rel='nofollow' target='_blank' class='external'>");
document.writeln("			  <i class='side-icon side-i3'></i>");
document.writeln("			  <p>开立账户</p>");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		  <li>");  
document.writeln("		<div class='side-hoverout last-hover-f' style='width: 0px; overflow: hidden;'>");
document.writeln("			  <p class='side-weix clearfix'>");
document.writeln("				<a href='https://download.mql5.com/cdn/web/gq.capital.inc/mt4/gqcapital4setup.exe' target='_blank'  class='side-down2-fon'><img src='../img/windows.png' alt='下载'><i>Windows版<br/>点击直接下载</i></a>");
document.writeln("				<span><img src='../img/android.png' alt='下载'><i>Android版<br/>扫描直接下载</i></span>");
document.writeln("				<span class='marginright0'><img src='../img/ios.png' alt='下载'><i>IOS版<br/>扫描直接下载</i></span>");
document.writeln("			  </p>");
document.writeln("			</div>");
document.writeln("			<a href='javascript:void(0)'>");
document.writeln("			  <i class='side-icon side-i11'></i>");
document.writeln("			  <p>平台下载</p>");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		</ul>");
document.writeln("</div>");